name: diffusion-mbir
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - scikit-image
  - sporco
  - tqdm
  - ninja
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - tensorboard
  - pip
  - pip:
      - ml_collections
      - ninja
      - climage
